package vue;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import control.DialogProjectCreatorControler;
import resources.Ressources;

/**
 * Classe affichage et interaction avec utilisateur pour la boite de dialogue de
 * creation de projets et groupes
 * 
 * @author THOME Alban
 * @category vue
 */
public class DialogProjectCreatorVue extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form ProjectCreatorDialog
	 */
	DialogProjectCreatorControler controler;

	public DialogProjectCreatorVue(java.awt.Frame parent, DialogProjectCreatorControler controler) {
		super(parent, false);
		this.controler = controler;
		initComponents();
		getRootPane().setDefaultButton(btnAnnuler);

		TFGroupeName.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void insertUpdate(DocumentEvent e) {
				controler.checkIfGroupExists(TFGroupeName.getText());
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				controler.checkIfGroupExists(TFGroupeName.getText());
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				controler.checkIfGroupExists(TFGroupeName.getText());
			}
		});

		TFProjectName.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void insertUpdate(DocumentEvent e) {
				controler.checkIfProjectExists(TFGroupeName.getText(), TFProjectName.getText());
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				controler.checkIfProjectExists(TFGroupeName.getText(), TFProjectName.getText());
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				controler.checkIfProjectExists(TFGroupeName.getText(), TFProjectName.getText());
			}
		});

		this.setLocationRelativeTo(parent);
		this.setIconImage(Ressources.logoGittse);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		jToolBar1 = new javax.swing.JToolBar();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		TFGroupeName = new javax.swing.JFormattedTextField();
		TFProjectName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		btnCreer = new javax.swing.JButton();
		btnAnnuler = new javax.swing.JButton();
		labelGroupExists = new javax.swing.JLabel();
		labelGroupExists.setText(" ");

		jToolBar1.setRollover(true);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Création d'un nouvel élément");
		setResizable(false);
		setType(java.awt.Window.Type.POPUP);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Créer un nouvel élément");

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel2.setText("Nom du groupe :");

		TFGroupeName.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				TFGroupeNameFocusLost(evt);
			}
		});
		TFGroupeName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TFGroupeNameActionPerformed(evt);
			}
		});

		TFProjectName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				TFProjectNameActionPerformed(evt);
			}
		});

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel3.setText("Nom du projet :");

		btnCreer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		btnCreer.setText("Créer");
		btnCreer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCreerActionPerformed(evt);
			}
		});

		btnAnnuler.setText("Annuler");
		btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAnnulerActionPerformed(evt);
			}
		});

		labelGroupExists.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(TFGroupeName, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(TFProjectName, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(btnCreer, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(btnAnnuler, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(labelGroupExists, javax.swing.JLayeredPane.DEFAULT_LAYER);

		labelProjectExists = new JLabel();
		labelProjectExists.setText(" ");
		labelProjectExists.setHorizontalAlignment(SwingConstants.CENTER);

		javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
		jLayeredPane1Layout.setHorizontalGroup(jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jLayeredPane1Layout.createSequentialGroup().addContainerGap(58, Short.MAX_VALUE)
						.addComponent(jLabel1).addContainerGap(58, Short.MAX_VALUE))
				.addGroup(jLayeredPane1Layout.createSequentialGroup().addContainerGap(33, Short.MAX_VALUE)
						.addGroup(jLayeredPane1Layout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(btnAnnuler, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addPreferredGap(ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
						.addGroup(jLayeredPane1Layout.createParallelGroup(Alignment.LEADING).addGroup(
								Alignment.TRAILING,
								jLayeredPane1Layout.createSequentialGroup().addGroup(jLayeredPane1Layout
										.createParallelGroup(Alignment.LEADING)
										.addComponent(labelProjectExists, GroupLayout.PREFERRED_SIZE, 140,
												GroupLayout.PREFERRED_SIZE)
										.addGroup(jLayeredPane1Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(TFGroupeName, GroupLayout.DEFAULT_SIZE, 140,
														Short.MAX_VALUE)
												.addComponent(labelGroupExists, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addComponent(TFProjectName, GroupLayout.PREFERRED_SIZE, 140,
												GroupLayout.PREFERRED_SIZE))
										.addContainerGap(33, Short.MAX_VALUE))
								.addGroup(Alignment.TRAILING,
										jLayeredPane1Layout
												.createSequentialGroup().addComponent(btnCreer,
														GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
												.addGap(47)))));
		jLayeredPane1Layout.setVerticalGroup(jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jLayeredPane1Layout.createSequentialGroup().addGap(21).addComponent(jLabel1).addGap(25)
						.addGroup(jLayeredPane1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2)
								.addComponent(TFGroupeName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addGap(5)
						.addComponent(labelGroupExists, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
						.addGap(12)
						.addGroup(jLayeredPane1Layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3)
								.addComponent(TFProjectName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED).addComponent(labelProjectExists).addGap(18)
						.addGroup(jLayeredPane1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jLayeredPane1Layout.createSequentialGroup()
										.addComponent(btnAnnuler, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGap(2))
								.addComponent(btnCreer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addGap(12)));
		jLayeredPane1.setLayout(jLayeredPane1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLayeredPane1));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void TFGroupeNameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_TFGroupeNameFocusLost
		controler.checkIfGroupExists(TFGroupeName.getText());
	}// GEN-LAST:event_TFGroupeNameFocusLost

	private void btnCreerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreerActionPerformed
		// TODO add your handling code here:
		controler.createProject(TFGroupeName.getText(), TFProjectName.getText());
		dispose();
	}// GEN-LAST:event_btnCreerActionPerformed

	private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAnnulerActionPerformed
		btnAnnuler.setActionCommand("Cancel");
		dispose();
	}// GEN-LAST:event_btnAnnulerActionPerformed

	private void TFProjectNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFProjectNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TFProjectNameActionPerformed

	private void TFGroupeNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TFGroupeNameActionPerformed

	}// GEN-LAST:event_TFGroupeNameActionPerformed

	private boolean groupIsBlocking = false;
	private boolean projectIsBlocking = false;

	public void setGroupAlreadyExists(final int existe) {
		SwingUtilities.invokeLater(new Runnable() { // pour affichage depuis le thread
			public void run() {
				groupIsBlocking = false;
				if (existe == 0) {
					labelGroupExists.setText("Projet personnel");
				} else if (existe == 1) {
					labelGroupExists.setText("Ce groupe existe");
				} else if (existe == 2) {
					labelGroupExists.setText("Ce groupe n'existe pas encore");
				} else {
					labelGroupExists.setText("Saisie invalide");
					groupIsBlocking = true;
				}
				btnCreer.setEnabled(!groupIsBlocking && !projectIsBlocking);
			}
		});
	}

	public void setProjectAlreadyExists(final int existe) {
		SwingUtilities.invokeLater(new Runnable() { // pour affichage depuis le thread
			public void run() {
				projectIsBlocking = false;
				if (existe == 0) {
					labelProjectExists.setText("Créer un groupe seulement");
				} else if (existe == 1) {
					labelProjectExists.setText("Ce projet existe déjà dans ce groupe");
					projectIsBlocking = true;
				} else if (existe == 2) {
					labelProjectExists.setText("Ce projet n'existe pas encore");
				} else {
					labelProjectExists.setText("Saisie invalide");
					projectIsBlocking = true;
				}
				btnCreer.setEnabled(!groupIsBlocking && !projectIsBlocking);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField TFGroupeName;
	private javax.swing.JTextField TFProjectName;
	private javax.swing.JButton btnAnnuler;
	private javax.swing.JButton btnCreer;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JLabel labelGroupExists;
	private JLabel labelProjectExists;
}
